---
abstract: 'advanced metadata for your distribution'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - Packaging
  - 'Semantic Web'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Install::RDF
name: Module-Install-RDF
no_index:
  directory:
    - inc
    - t
requires:
  Module::Install: 1.00
  Module::Runtime: 0
  Object::ID: 0
  RDF::TriN3: 0.201
  RDF::Trine: 0.135
  URI::file: 4.0
  perl: 5.005
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Module-Install-RDF
  homepage: https://metacpan.org/release/Module-Install-RDF
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-module-install-rdf
version: 0.008
